var getScoreArray = [
    { text: "選擇", value: "default" },
    { text: "對方失誤", value: "enemy-error" },
    { text: "攻擊得分", value: "attack-get" },
    { text: "吊球得分", value: "tip-get" },
    { text: "發球得分", value: "ace" },
    { text: "攔網得分", value: "block-get" }
]
var lossScoreArray = [
    { text: "選擇", value: "default" },
    { text: "攻擊失誤", value: "attack-loss" },
    { text: "發球失誤", value: "serve-loss" },
    { text: "接球失誤", value: "pass-loss" },
    { text: "攔網失誤", value: "block-loss" },
    { text: "舉球失誤", value: "set-loss" },
    { text: "犯規失誤", value: "error" }
]
var memberNum = {
    0: "子勻",
    1: "高峻",
    2: "柏佑",
    3: "健翔",
    4: "靄宏",
    5: "嘉澤",
    6: "紹華",
    7: "浩澤",
    8: "鼎鈞",
    9: "偲睿",
    10: "敬易",
    11: "彥廷",
    12: "明廷",
    13: "皓澤",
    14: "培軒",
    15: "佑瑜",
    16: "修宏",
    17: "銘宏",
    18: "承翰",
    19: "彥瑋",
    20: "子毓",
    21: "聖宇",
    24: "辰臻",
    25: "承哲",
    26: "運昌",
    29: "鴻縉",
    30: "祐禎",
    33: "允文",
    60: "戴宇",
    69: "城偉",
    88: "奕辰",
    99: "俊霖",
};
